version: 0.2

phases:
  install:
     runtime-versions:
     nodejs: 22
     commands:
     -echo Installing source NPM dependencies...
     -npm Installing
     build:
     commands:
     - echo build started on 'date'
     - echo building the node.js application...
     - npm run build
     post_build:
     commands:
     -echo build completed on 'date'

     artifacts:
     files:
     - '**/*'
base-directory: dist

